import type { Metadata } from "next";
import { hadwick, neuecomic } from "@/styles/fonts";
import NavBar from "@/components/NavBar";
import Providers from "@/components/Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mirrors Mind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hadwick.variable} ${neuecomic.variable}`}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
