import type { Metadata } from "next";
import { hadwick, heroin } from "@/styles/fonts";
import NavBar from "@/components/NavBar";
import Providers from "@/components/Providers";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Mirrors Mind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hadwick.variable} ${heroin.variable}`}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
